FRAMEWORK/DJANGO/DEVSEARCH/devsearch/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path("admin/", admin.site.urls),
            path("projects/", include("projects.urls")),
            path("", include("users.urls")),]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FRAMEWORK/DJANGO/DEVSEARCH/users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userprofile, name='userprofile'),
]

FRAMEWORK/DJANGO/DEVSEARCH/projects/models.py
from django.db import models
from users.models import Profile
import uuid

# Create your models here.


# This is a table called Project
class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(
        null=True, blank=True
    )  # null is to allow or permit an empty record into the database while blank informs django that it can accept a record which is empty
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.URLField(max_length=2000, null=True, blank=True)
    source_link = models.URLField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, db_index=True, editable=False
    )

    def __str__(self):
        return self.title


# This is a table called Review
class Review(models.Model):
    VOTE = (
        ("up", "Up Vote"),
        ("down", "Down Vote"),
    )
    # owner =
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, db_index=True, editable=False
    )

    def __str__(self):
        return self.value


# This is a table called Tag
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, db_index=True, editable=False
    )

    def __str__(self):
        return self.name

FRAMEWORK/DJANGO/DEVSEARCH/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import URLValidator
import uuid
# Create your models here.

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True) 
    location = models.CharField(max_length=200, null=True, blank=True) 
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(blank=True, null=True,)
    profile_image = models.ImageField(null=True, blank=True, upload_to="profiles/", default="profiles/user-default.png")
    social_github = models.URLField(validators=[URLValidator(regex='https://github.com')], max_length=200, null=True, blank=True)
    social_linkedin = models.URLField(validators=[URLValidator(regex='https://www.linkedin.com')], max_length=200, null=True, blank=True)
    social_website = models.URLField(validators=[URLValidator(regex='https://')], max_length=200, null=True, blank=True)
    social_twitter = models.URLField(validators=[URLValidator(regex='https://twitter.com')], max_length=200, null=True, blank=True)
    social_youtube = models.URLField(validators=[URLValidator(regex='https://www.youtube.com')], max_length=200, null=True, blank=True)
    social_stackoverflow = models.URLField(validators=[URLValidator(regex='https://stackoverflow.com')], max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, db_index=True, editable=False
    )
    
    def __str__(self):
        return str(self.username)

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, db_index=True, editable=False
    )
    
    def __str__(self):
        return str(self.name)
    
    
# @receiver(post_save, sender=Profile)
def createprofile(sender, instance, created, **kwergs):
    if created:
        user = instance
        profile = Profile.objects.create(
            user=user,
            username=user.username,
            email=user.email,
            name=user.first_name,
        )

# @receiver(post_delete, sender=Profile)
def deleteuser(sender, instance, **kwergs):
    user = instance.user
    user.delete()
    


# post_save.connect(createprofile, sender=User)
# post_delete.connect(deleteuser, sender=Profile)

FRAMEWORK/DJANGO/DEVSEARCH/users/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)

def userprofile(request, pk):
    profile = Profile.objects.get(id=pk)
    topskills = profile.skill_set.exclude(description__exact="")
    lowskills = profile.skill_set.filter(description="")
    context={'profile': profile, 'topskills': topskills, 'lowskills': lowskills}
    return render(request, 'users/user-profile.html', context)

FRAMEWORK/DJANGO/DEVSEARCH/users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form class="form" action="#" method="get">
                <div class="form__field">
                    <label for="formInput#search">Search Developers </label>
                    <input class="input input--text" id="formInput#search" type="text" name="text"
                    placeholder="Search by developer name" />
                </div>

                <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
        <div class="grid grid--three">

            {% for profile in profiles %}
            <div class="column card">
            <div class="dev">
                <a href="{% url 'userprofile' profile.id %}" class="card__body">
                <div class="dev__profile">
                    <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                    <div class="dev__meta">
                    <h3>{{ profile.name }}</h3>
                    <h5>{{ profile.short_intro|slice:"60"}}</h5>
                    </div>
                </div>
                <p class="dev__info">
                    {{ profile.bio|slice:"150" }}
                </p>
                <div class="dev__skills">
                {% for skill in profile.skill_set.all %}
                    <span class="tag tag--pill tag--main">
                        <small>{{ skill.name }} </small>
                    </span>
                {% endfor %}
                </div>
                </a>
            </div>
            </div>
            {% endfor %}

        </div>
        </div>
    </section>

</main>

{% endblock%}

FRAMEWORK/DJANGO/DEVSEARCH/users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
        <div class="column column--1of3">
            <div class="card text-center">
            <div class="card__body dev">
                <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                <h2 class="dev__name">{{ profile.name}}</h2>
                <p class="dev__title">{{ profile.short_intro}}</p>
                <p class="dev__location">Based in {{ profile.location}}</p>
                <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                    <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fab fa-github fa-2x"></i></a>
                </li>
                {% endif %}
                {% if profile.social_stackoverflow %}
                <li>
                    <a title="Stackoverflow" href="{{ profile.social_stackoverflow }}" target="_blank"><i class="fab fa-stack-overflow fa-2x"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                <li>
                    <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                    <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="fab fa-linkedin fa-2x"></i></a>
                </li>
                {% endif %}
                {% if profile.social_youtube %}
                <li>
                    <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                    <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa-sharp fa-solid fa-globe fa-2x"></i></a>
                </li>
                {% endif %}
                </ul>
                <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
            </div>
        </div>
        <div class="column column--2of3">
            <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
            </div>
            <div class="devInfo">
            {% if topskills %}
                <h3 class="devInfo__title">Skills</h3>
            {% endif %}
            <div class="devInfo__skills">

                {% for topskill in topskills%}
                <div class="devSkill">
                <h4 class="devSkill__title">{{ topskill.name }}</h4>
                <p class="devSkill__info">
                    {{ topskill.description }}
                </p>
                </div>
                {% endfor %}

                {% if lowskills %}
                    <h3 class="devInfo__subtitle">Other Skills</h3>
                {% endif %}
                <div class="devInfo__otherSkills">

                {% for lowskill in lowskills %}
                <span class="tag tag--pill tag--sub tag--lg">
                    mall>{{ lowskill.name }}</small>
                </span>
                {% endfor%}

                
                </div>
            </div>
            </div>
            <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in profile.project_set.all %}
                <div class="column">
                <div class="card project">
                    <a href="{% url 'singleproject' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                        <h3 class="project__title">{{ project.title}}</h3>
                        <p><a class="project__author" href="{% url 'userprofile' profile.id %}">By {{ project.owner.name }} </a></p>
                        <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
                        </p>
                        <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                            <small>{{ tag }}</small>
                        </span>
                        {% endfor %}
                        </div>
                    </div>
                    </a>
                </div>
                </div>
            {% endfor %}

            </div>
            </div>
        </div>
        </div>
    </div>
</main>

{% endblock %}